services:
  mongodb:
    image: mongo:7.0
    container_name: certshield-db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    container_name: certshield-api
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      - MONGODB_URL=mongodb://admin:password@mongodb:27017/CertShield?authSource=admin
    volumes:
      - ./backend/keys:/app/keys
      - ./backend:/app
    depends_on:
      - mongodb
    restart: unless-stopped

  frontend-admin:
    build:
      context: ./frontend-admin
    container_name: certshield-admin
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    volumes:
      - ./frontend-admin/src:/app/src
      - ./frontend-admin/public:/app/public
    depends_on:
      - backend
    restart: unless-stopped

  frontend-portal:
    build:
      context: ./frontend-portal
    container_name: certshield-portal
    ports:
      - "3001:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    volumes:
      - ./frontend-portal/src:/app/src
      - ./frontend-portal/public:/app/public
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mongodb_data:
    name: certshield_mongo_volume
